orchestrator:
  ros__parameters:
    pre_approach_distance: 0.15
    approach_distance: 0.06
    gripper_open_value: 0.0
    gripper_close_value: 0.31
    home_z_position: 1.25
    place_offset_x: 0.1
    place_offset_z: 0.1
