name: Build and Compile ROS2 workspace
#add git actions
on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  ROS_CI:
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        ros2_distribution:
          - humble

        include: 
          # ROS 2 Humble Hawksbill
          - docker_image: osrf/ros:humble-desktop-full
            ros_distribution: humble
            ros_version: 2
    
    container:
        image: ${{ matrix.docker_image }}
    
    steps:
      - name: Setup workspace
        run: mkdir -p ros_ws/src

      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y \
            software-properties-common \
            python3-pip \
            python3-colcon-common-extensions \
            nano \
            git \
            wget \
            vim \
            tar xz-utils \
            libx11-6 libxcb1 libxau6 libgl1-mesa-dev \
            xvfb dbus-x11 x11-utils libxkbcommon-x11-0 \
            libavcodec-dev libavformat-dev libswscale-dev \
            python3-venv libraw1394-11 libmpfr6 libusb-1.0-0 \
            xsltproc \
            ros-humble-joint-state-publisher-gui \
            ros-humble-robot-state-publisher \
            ros-humble-ros2-control \
            ros-humble-ros2-controllers \
            ros-humble-xacro \
            ros-humble-moveit \
            ros-humble-gazebo-ros-pkgs \
            ros-humble-gazebo-ros2-control \
            ros-humble-ros-gz \
            libxcb-xinerama0 && \
          apt-get clean && rm -rf /var/lib/apt/lists/*

      - name: Install Python packages
        run: |
          pip3 install pyzmq cbor2 pyserial flask flask-ask-sdk ask-sdk xmlschema

      - name: Checkout code and setup workspace
        uses: actions/checkout@v4
        with:
          path: ros_ws/src

      - name: Clone BehaviorTree.ROS2
        run: |
          cd ros_ws/src
          git clone https://github.com/BehaviorTree/BehaviorTree.ROS2.git



      - name: Clone BehaviorTree.CPP
        run: |
          cd ros_ws/src
          git clone https://github.com/BehaviorTree/BehaviorTree.CPP.git

      - name: Run install.sh
        run: yes y | ./install.sh -d
        working-directory: ros_ws/src

      - name: Setup git credentials
        run: |
          git config --global url."https://${{ secrets.GH_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      
      - name: Initialize rosdep
        run: |
          apt-get update && apt-get install -y python3-rosdep
          rosdep init || true
          rosdep update
          
      - name: Build selected packages
        shell: bash
        run: |
          source /opt/ros/${{ matrix.ros_distribution }}/setup.bash
          cd ros_ws
          colcon build --packages-select \
            cr_motion_core \
            cr_controller \
            cr_gui \
            cr_hw_configuration \
            cr_interfaces \
            cr_moveit \
            cr_remote_assistant \
            cr_scene_management

        # - name: Build only
        #   uses: ros-tooling/action-ros-ci@v0.3
        #   with:
        #     target-ros2-distro: ${{ matrix.ros_distribution }}
        #     package-name: |
        #       cr_motion_core
        #       cr_controller
        #       cr_gui
        #       cr_hw_configuration
        #       cr_interfaces
        #       cr_moveit
        #       cr_remote_assistant
        #       cr_scene_management
        #     skip-tests: true
        #   env:
        #     AMENT_LINT_AUTO_EXCLUDE: "ament_cmake_flake8 ament_cmake_pep257 ament_cmake_xmllint ament_cmake_lint_cmake"

          #   cr_vision
          #   BehaviorTree.CPP
          #   BehaviorTree.ROS2
          #   robotiq_description
          #   ur_description
          #   cr_bt_common
          #   cr_bt_pick_place
          #   cr_bt_orchestrator
